### ISSUE TITLE
Add citation file?

### ISSUE THREAD

**Issue by kinow** [filcfig/PCP#1]
Hey, found this paper from Twitter, and was interested to see what workflow manager you used (thought it would be something CWL-related, but Snakemake is nice too :+1: ).

The citation in the README file can now be turned into a separate file, like the LICENSE file: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files

That way the repository will have a button where users familiar with this feature can quickly search it. I guess that will be used in search & other integration services of GitHub too.

Great job on the paper and thanks for sharing the source code openly here!

Bruno

**Comment by haansi** [comment]
Thanks Bruno for pointing to this - I added a citation.cff file now - see 8a6edef2f515ac5da32ba61ee3f3e11c8cc485b6

**Comment by kinow** [comment]
Brilliant! The UI is now showing the citation on the right sidebar. Thanks @haansi !

![image](https://user-images.githubusercontent.com/304786/140721534-987f2840-5d63-424e-bb6a-5faeca70bb84.png)
